runtime: nodejs8
instance_class: F1
env_variables:
  BUCKET_NAME: "scode-test"
  NODE_ENV: production
handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
