export const ANALYTICS_ACTION_LOCATION_OPEN = 'open';
export const ANALYTICS_ACTION_LOCATION_CLOSE = 'close';
export const ANALYTICS_ACTION_SELECT_SUB_CATEGORY = 'select';
export const ANALYTICS_ACTION_DESELECT_SUB_CATEGORY = 'deselect';
