version: '3'

services:
  app:
    image: node:10
    volumes:
      - nodemodules:/app/node_modules
      - ../:/app
    working_dir: /app
    command: npm run dev --  --host 0.0.0.0
    ports:
      - 3000:3000
volumes:
  nodemodules:
    external: true
